// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 20 Feb 2017 18:12:38 UYT.
// By https://git.io/cgogen. DO NOT EDIT.

package nk

/*
#include "nuklear.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// IncludeVertexBufferOutput as defined in nuklear/<predefine>:20
	IncludeVertexBufferOutput = 1
	// IncludeFixedTypes as defined in nuklear/<predefine>:21
	IncludeFixedTypes = 1
	// IncludeStandardIo as defined in nuklear/<predefine>:22
	IncludeStandardIo = 1
	// IncludeDefaultAllocator as defined in nuklear/<predefine>:23
	IncludeDefaultAllocator = 1
	// IncludeFontBaking as defined in nuklear/<predefine>:24
	IncludeFontBaking = 1
	// IncludeDefaultFont as defined in nuklear/<predefine>:25
	IncludeDefaultFont = 1
	// Undefined as defined in nk/nuklear.h:253
	Undefined = (-1.0)
	// UtfInvalid as defined in nk/nuklear.h:254
	UtfInvalid = 0xFFFD
	// UtfSize as defined in nk/nuklear.h:255
	UtfSize = 4
	// InputMax as defined in nk/nuklear.h:257
	InputMax = 16
	// MaxNumberBuffer as defined in nk/nuklear.h:260
	MaxNumberBuffer = 64
	// ScrollbarHidingTimeout as defined in nk/nuklear.h:263
	ScrollbarHidingTimeout = 4.0
	// TexteditUndostatecount as defined in nk/nuklear.h:1626
	TexteditUndostatecount = 99
	// TexteditUndocharcount as defined in nk/nuklear.h:1630
	TexteditUndocharcount = 999
	// ChartMaxSlot as defined in nk/nuklear.h:2616
	ChartMaxSlot = 4
	// WindowMaxName as defined in nk/nuklear.h:2701
	WindowMaxName = 64
	// ButtonBehaviorStackSize as defined in nk/nuklear.h:2810
	ButtonBehaviorStackSize = 8
	// FontStackSize as defined in nk/nuklear.h:2814
	FontStackSize = 8
	// StyleItemStackSize as defined in nk/nuklear.h:2818
	StyleItemStackSize = 16
	// FloatStackSize as defined in nk/nuklear.h:2822
	FloatStackSize = 32
	// VectorStackSize as defined in nk/nuklear.h:2826
	VectorStackSize = 16
	// FlagsStackSize as defined in nk/nuklear.h:2830
	FlagsStackSize = 32
	// ColorStackSize as defined in nk/nuklear.h:2834
	ColorStackSize = 32
	// Float as defined in nk/nuklear.h:2848
	Float = 0
	// Pi as defined in nk/nuklear.h:2961
	Pi = 3.141592654
	// MaxFloatPrecision as defined in nk/nuklear.h:2963
	MaxFloatPrecision = 2
)

// Heading as declared in nk/nuklear.h:461
type Heading int32

// Heading enumeration from nk/nuklear.h:461
const (
	Up = iota
	Right
	Down
	Left
)

// ButtonBehavior as declared in nk/nuklear.h:462
type ButtonBehavior int32

// ButtonBehavior enumeration from nk/nuklear.h:462
const (
	ButtonDefault = iota
	ButtonRepeater
)

// Modify as declared in nk/nuklear.h:463
type Modify int32

// Modify enumeration from nk/nuklear.h:463
const (
	Fixed      = False
	Modifiable = True
)

// Orientation as declared in nk/nuklear.h:464
type Orientation int32

// Orientation enumeration from nk/nuklear.h:464
const (
	Vertical = iota
	Horizontal
)

// CollapseStates as declared in nk/nuklear.h:465
type CollapseStates int32

// CollapseStates enumeration from nk/nuklear.h:465
const (
	Minimized = False
	Maximized = True
)

// ShowStates as declared in nk/nuklear.h:466
type ShowStates int32

// ShowStates enumeration from nk/nuklear.h:466
const (
	Hidden = False
	Shown  = True
)

// ChartType as declared in nk/nuklear.h:467
type ChartType int32

// ChartType enumeration from nk/nuklear.h:467
const (
	ChartLines = iota
	ChartColumn
	ChartMax
)

// ChartEvent as declared in nk/nuklear.h:468
type ChartEvent int32

// ChartEvent enumeration from nk/nuklear.h:468
const (
	ChartHovering = 0x01
	ChartClicked  = 0x02
)

// ColorFormat as declared in nk/nuklear.h:469
type ColorFormat int32

// ColorFormat enumeration from nk/nuklear.h:469
const (
	ColorFormatRGB = iota
	ColorFormatRGBA
)

// PopupType as declared in nk/nuklear.h:470
type PopupType int32

// PopupType enumeration from nk/nuklear.h:470
const (
	PopupStatic = iota
	PopupDynamic
)

// LayoutFormat as declared in nk/nuklear.h:471
type LayoutFormat int32

// LayoutFormat enumeration from nk/nuklear.h:471
const (
	Dynamic = iota
	Static
)

// TreeType as declared in nk/nuklear.h:472
type TreeType int32

// TreeType enumeration from nk/nuklear.h:472
const (
	TreeNode = iota
	TreeTab
)

// AntiAliasing as declared in nk/nuklear.h:473
type AntiAliasing int32

// AntiAliasing enumeration from nk/nuklear.h:473
const (
	AntiAliasingOff = iota
	AntiAliasingOn
)

// SymbolType as declared in nk/nuklear.h:514
type SymbolType int32

// SymbolType enumeration from nk/nuklear.h:514
const (
	SymbolNone = iota
	SymbolX
	SymbolUnderscore
	SymbolCircleSolid
	SymbolCircleOutline
	SymbolRectSolid
	SymbolRectOutline
	SymbolTriangleUp
	SymbolTriangleDown
	SymbolTriangleLeft
	SymbolTriangleRight
	SymbolPlus
	SymbolMinus
	SymbolMax
)

// Keys as declared in nk/nuklear.h:531
type Keys int32

// Keys enumeration from nk/nuklear.h:531
const (
	KeyNone = iota
	KeyShift
	KeyCtrl
	KeyDel
	KeyEnter
	KeyTab
	KeyBackspace
	KeyCopy
	KeyCut
	KeyPaste
	KeyUp
	KeyDown
	KeyLeft
	KeyRight
	KeyTextInsertMode
	KeyTextReplaceMode
	KeyTextResetMode
	KeyTextLineStart
	KeyTextLineEnd
	KeyTextStart
	KeyTextEnd
	KeyTextUndo
	KeyTextRedo
	KeyTextSelectAll
	KeyTextWordLeft
	KeyTextWordRight
	KeyScrollStart
	KeyScrollEnd
	KeyScrollDown
	KeyScrollUp
	KeyMax
)

// Buttons as declared in nk/nuklear.h:570
type Buttons int32

// Buttons enumeration from nk/nuklear.h:570
const (
	ButtonLeft = iota
	ButtonMiddle
	ButtonRight
	ButtonMax
)

// StyleColors as declared in nk/nuklear.h:577
type StyleColors int32

// StyleColors enumeration from nk/nuklear.h:577
const (
	ColorText = iota
	ColorWindow
	ColorHeader
	ColorBorder
	ColorButton
	ColorButtonHover
	ColorButtonActive
	ColorToggle
	ColorToggleHover
	ColorToggleCursor
	ColorSelect
	ColorSelectActive
	ColorSlider
	ColorSliderCursor
	ColorSliderCursorHover
	ColorSliderCursorActive
	ColorProperty
	ColorEdit
	ColorEditCursor
	ColorCombo
	ColorChart
	ColorChartColor
	ColorChartColorHighlight
	ColorScrollbar
	ColorScrollbarCursor
	ColorScrollbarCursorHover
	ColorScrollbarCursorActive
	ColorTabHeader
	ColorCount
)

// StyleCursor as declared in nk/nuklear.h:609
type StyleCursor int32

// StyleCursor enumeration from nk/nuklear.h:609
const (
	CursorArrow = iota
	CursorText
	CursorMove
	CursorResizeVertical
	CursorResizeHorizontal
	CursorResizeTopLeftDownRight
	CursorResizeTopRightDownLeft
	CursorCount
)

// WidgetLayoutStates as declared in nk/nuklear.h:620
type WidgetLayoutStates int32

// WidgetLayoutStates enumeration from nk/nuklear.h:620
const (
	WidgetInvalid = iota
	WidgetValid
	WidgetRom
)

// WidgetStates as declared in nk/nuklear.h:627
type WidgetStates int32

// WidgetStates enumeration from nk/nuklear.h:627
const (
	WidgetStateModified = (1 << (1))
	WidgetStateInactive = (1 << (2))
	WidgetStateEntered  = (1 << (3))
	WidgetStateHover    = (1 << (4))
	WidgetStateActived  = (1 << (5))
	WidgetStateLeft     = (1 << (6))
	WidgetStateHovered  = WidgetStateHover | WidgetStateModified
	WidgetStateActive   = WidgetStateActived | WidgetStateModified
)

// TextAlign as declared in nk/nuklear.h:639
type TextAlign int32

// TextAlign enumeration from nk/nuklear.h:639
const (
	TextAlignLeft     = 0x01
	TextAlignCentered = 0x02
	TextAlignRight    = 0x04
	TextAlignTop      = 0x08
	TextAlignMiddle   = 0x10
	TextAlignBottom   = 0x20
)

// TextAlignment as declared in nk/nuklear.h:647
type TextAlignment int32

// TextAlignment enumeration from nk/nuklear.h:647
const (
	TextLeft     = TextAlignMiddle | TextAlignLeft
	TextCentered = TextAlignMiddle | TextAlignCentered
	TextRight    = TextAlignMiddle | TextAlignRight
)

// EditFlags as declared in nk/nuklear.h:654
type EditFlags int32

// EditFlags enumeration from nk/nuklear.h:654
const (
	EditDefault            = iota
	EditReadOnly           = (1 << (0))
	EditAutoSelect         = (1 << (1))
	EditSigEnter           = (1 << (2))
	EditAllowTab           = (1 << (3))
	EditNoCursor           = (1 << (4))
	EditSelectable         = (1 << (5))
	EditClipboard          = (1 << (6))
	EditCtrlEnterNewline   = (1 << (7))
	EditNoHorizontalScroll = (1 << (8))
	EditAlwaysInsertMode   = (1 << (9))
	EditMultiline          = (1 << (11))
	EditGotoEndOnActivate  = (1 << (12))
)

// EditTypes as declared in nk/nuklear.h:669
type EditTypes int32

// EditTypes enumeration from nk/nuklear.h:669
const (
	EditSimple = EditAlwaysInsertMode
	EditField  = EditSimple | EditSelectable | EditClipboard
	EditBox    = EditAlwaysInsertMode | EditSelectable | EditMultiline | EditAllowTab | EditClipboard
	EditEditor = EditSelectable | EditMultiline | EditAllowTab | EditClipboard
)

// EditEvents as declared in nk/nuklear.h:675
type EditEvents int32

// EditEvents enumeration from nk/nuklear.h:675
const (
	EditActive      = (1 << (0))
	EditInactive    = (1 << (1))
	EditActivated   = (1 << (2))
	EditDeactivated = (1 << (3))
	EditCommited    = (1 << (4))
)

// PanelFlags as declared in nk/nuklear.h:682
type PanelFlags int32

// PanelFlags enumeration from nk/nuklear.h:682
const (
	WindowBorder         = (1 << (0))
	WindowMovable        = (1 << (1))
	WindowScalable       = (1 << (2))
	WindowClosable       = (1 << (3))
	WindowMinimizable    = (1 << (4))
	WindowNoScrollbar    = (1 << (5))
	WindowTitle          = (1 << (6))
	WindowScrollAutoHide = (1 << (7))
	WindowBackground     = (1 << (8))
)

// FontCoordType as declared in nk/nuklear.h:1320
type FontCoordType int32

// FontCoordType enumeration from nk/nuklear.h:1320
const (
	CoordUv = iota
	CoordPixel
)

// FontAtlasFormat as declared in nk/nuklear.h:1391
type FontAtlasFormat int32

// FontAtlasFormat enumeration from nk/nuklear.h:1391
const (
	FontAtlasAlpha8 = iota
	FontAtlasRgba32
)

// AllocationType as declared in nk/nuklear.h:1488
type AllocationType int32

// AllocationType enumeration from nk/nuklear.h:1488
const (
	BufferFixed = iota
	BufferDynamic
)

// BufferAllocationType as declared in nk/nuklear.h:1493
type BufferAllocationType int32

// BufferAllocationType enumeration from nk/nuklear.h:1493
const (
	BufferFront = iota
	BufferBack
	BufferMax
)

// TextEditType as declared in nk/nuklear.h:1656
type TextEditType int32

// TextEditType enumeration from nk/nuklear.h:1656
const (
	TextEditSingleLine = iota
	TextEditMultiLine
)

// TextEditMode as declared in nk/nuklear.h:1661
type TextEditMode int32

// TextEditMode enumeration from nk/nuklear.h:1661
const (
	TextEditModeView = iota
	TextEditModeInsert
	TextEditModeReplace
)

// CommandType as declared in nk/nuklear.h:1761
type CommandType int32

// CommandType enumeration from nk/nuklear.h:1761
const (
	CommandTypeNop = iota
	CommandTypeScissor
	CommandTypeLine
	CommandTypeCurve
	CommandTypeRect
	CommandTypeRectFilled
	CommandTypeRectMultiColor
	CommandTypeCircle
	CommandTypeCircleFilled
	CommandTypeArc
	CommandTypeArcFilled
	CommandTypeTriangle
	CommandTypeTriangleFilled
	CommandTypePolygon
	CommandTypePolygonFilled
	CommandTypePolyline
	CommandTypeText
	CommandTypeImage
)

// CommandClipping as declared in nk/nuklear.h:1933
type CommandClipping int32

// CommandClipping enumeration from nk/nuklear.h:1933
const (
	ClippingOff = False
	ClippingOn  = True
)

// DrawListStroke as declared in nk/nuklear.h:2043
type DrawListStroke int32

// DrawListStroke enumeration from nk/nuklear.h:2043
const (
	StrokeOpen   = False
	StrokeClosed = True
)

// DrawVertexLayoutAttribute as declared in nk/nuklear.h:2050
type DrawVertexLayoutAttribute int32

// DrawVertexLayoutAttribute enumeration from nk/nuklear.h:2050
const (
	VertexPosition = iota
	VertexColor
	VertexTexcoord
	VertexAttributeCount
)

// DrawVertexLayoutFormat as declared in nk/nuklear.h:2057
type DrawVertexLayoutFormat int32

// DrawVertexLayoutFormat enumeration from nk/nuklear.h:2057
const (
	FormatSchar = iota
	FormatSshort
	FormatSint
	FormatUchar
	FormatUshort
	FormatUint
	FormatFloat
	FormatDouble
	FormatColorBegin
	FormatR8g8b8 = FormatColorBegin
	FormatR16g15b16
	FormatR32g32b32
	FormatR8g8b8a8
	FormatR16g15b16a16
	FormatR32g32b32a32
	FormatR32g32b32a32Float
	FormatR32g32b32a32Double
	FormatRgb32
	FormatRgba32
	FormatColorEnd = FormatRgba32
	FormatCount
)

// StyleItemType as declared in nk/nuklear.h:2176
type StyleItemType int32

// StyleItemType enumeration from nk/nuklear.h:2176
const (
	StyleItemColor = iota
	StyleItemImage
)

// StyleHeaderAlign as declared in nk/nuklear.h:2517
type StyleHeaderAlign int32

// StyleHeaderAlign enumeration from nk/nuklear.h:2517
const (
	HeaderLeft = iota
	HeaderRight
)

// PanelType as declared in nk/nuklear.h:2619
type PanelType int32

// PanelType enumeration from nk/nuklear.h:2619
const (
	PanelWindow     = (1 << (0))
	PanelGroup      = (1 << (1))
	PanelPopup      = (1 << (2))
	PanelContextual = (1 << (4))
	PanelCombo      = (1 << (5))
	PanelMenu       = (1 << (6))
	PanelTooltip    = (1 << (7))
)

// PanelSet as declared in nk/nuklear.h:2628
type PanelSet int32

// PanelSet enumeration from nk/nuklear.h:2628
const (
	PanelSetNonblock = PanelContextual | PanelCombo | PanelMenu | PanelTooltip
	PanelSetPopup    = PanelSetNonblock | PanelPopup
	PanelSetSub      = PanelSetPopup | PanelGroup
)

// WindowFlags as declared in nk/nuklear.h:2705
type WindowFlags int32

// WindowFlags enumeration from nk/nuklear.h:2705
const (
	WindowPrivate   = (1 << (10))
	WindowDynamic   = WindowPrivate
	WindowRom       = (1 << (11))
	WindowHidden    = (1 << (12))
	WindowClosed    = (1 << (13))
	WindowMinimized = (1 << (14))
	WindowRemoveRom = (1 << (15))
)

const (
	// False as declared in nk/nuklear.h:448
	False = iota

	// NOTE: For some strange reason there used to be
	//       three possible boolean values here.

	// True as declared in nk/nuklear.h:448
	True
)
